STRINGS = {
    "restart_msg": "<emoji id=5195083327597456039>🌙</emoji> <code>Xioca</code> <b>has been fully restarted!</b>\n<emoji id=5386367538735104399>⌛</emoji> <b>Restart took <code>{sec}</code> sec.</b>",
    "update_msg": "<emoji id=5195083327597456039>🌙</emoji> <b>Xioca updated successfully!</b>\n<emoji id=5386367538735104399>⌛</emoji> <b>Update took <code>{sec}</code> sec.</b>",
    "install_req": "⏳ Installing dependencies: <code>{r}</code>...",
    "auto_install_req": "<emoji id=6039802767931871481>⬇️</emoji> Auto-installing <code>{mpkg}</code>...",
    "error_command": "<emoji id=5210952531676504517>❌</emoji> <b>An error occurred while executing the command: </b> <code>{text}</code>\n<emoji id=5440660757194744323>‼️</emoji> <b>Error:</b>\n<code>{exc}</code>",
    "show_traceback": "🐞 Show Traceback",
    "best_module_name": "<emoji id=5312383351217201533>⚠️</emoji> <b>No exact match found, so the closest result has been applied</b>",
    "file_not_found": "<emoji id=5210952531676504517>❌</emoji> <b>Modules folder not found</b>",
    "create_inline_form": "🌙 <b>Creating inline form...</b>",
    "create_inline_form_premium": "<emoji id=5199885066674661599>🌙</emoji><emoji id=5199427893175807183>🌙</emoji><emoji id=5199518289352486689>🌙</emoji> <b>Creating inline form...</b>",
    "inline_forbidden": "🚫 <b>Inline mode is not available in this chat</b>",
    "inline_not_found": "❌ <b>No such inline command found</b>",
    "inline_bot_forbidden": "🚫 Access denied",
    "inline_info": "😎 This is <code>Xioca</code>. An excellent userbot with a large number of commands and modules.\n\n❓ <b>How to install?</b>\nTo <b>install</b>, please use the <a href='https://xioca.ferz.live'>website</a>.\n\n🌟 <b>Features:</b>\n- Convenient control via commands.\n- Inline mode support.\n- Modular architecture for functionality expansion.\n- Regular updates and support.\n\n📚 <b>Documentation:</b>\nYou can learn more about features and setup in the <a href='https://github.com/shashachkaaa/Xioca'>documentation</a>.\n\n🛠 <b>Support:</b>\nIf you have any questions, please contact the <a href='https://t.me/XiocaSUPPORT'>support chat</a>.",
    "inline_description": "Learn more about Xioca and how to install it.",
    "inline_commands": "👇 <b>Available commands</b>\n{commands}",
    "commands_title": "Available commands",
    "inline_error": "Error",
    "installing_deps_header": "<emoji id=5884479287171485878>📦</emoji> Installing dependencies:",
    "dragon_doc": "This is a Dragon-Userbot module that does not provide for adding a description.",
    "not_description": "No description"
}