STRINGS = {
    "restart_msg": "<emoji id=5195083327597456039>🌙</emoji> <code>Xioca</code> <b>se ha reiniciado completamente.</b>\n<emoji id=5386367538735104399>⌛</emoji> <b>El reinicio tomó <code>{sec}</code> seg.</b>",
    "update_msg": "<emoji id=5195083327597456039>🌙</emoji> <b>¡Xioca actualizada con éxito!</b>\n<emoji id=5386367538735104399>⌛</emoji> <b>La actualización tomó <code>{sec}</code> seg.</b>",
    "install_req": "⏳ Instalando dependencias: <code>{r}</code>...",
    "auto_install_req": "<emoji id=6039802767931871481>⬇️</emoji> Auto-instalación de <code>{mpkg}</code>...",
    "error_command": "<emoji id=5210952531676504517>❌</emoji> <b>Error al ejecutar el comando: </b> <code>{text}</code>\n<emoji id=5440660757194744323>‼️</emoji> <b>Error:</b>\n<code>{exc}</code>",
    "show_traceback": "🐞 Mostrar Traceback",
    "best_module_name": "<emoji id=5312383351217201533>⚠️</emoji> <b>No se encontró una coincidencia exacta, se usó el resultado más cercano</b>",
    "file_not_found": "<emoji id=5210952531676504517>❌</emoji> <b>Carpeta modules no encontrada</b>",
    "create_inline_form": "🌙 <b>Creando formulario inline...</b>",
    "create_inline_form_premium": "<emoji id=5199885066674661599>🌙</emoji><emoji id=5199427893175807183>🌙</emoji><emoji id=5199518289352486689>🌙</emoji> <b>Creando formulario inline...</b>",
    "inline_forbidden": "🚫 <b>Modo inline no disponible en este chat</b>",
    "inline_not_found": "❌ <b>No existe tal comando inline</b>",
    "inline_bot_forbidden": "🚫 Acceso denegado",
    "inline_info": "😎 Esto es <code>Xioca</code>. Un excelente userbot con una gran cantidad de comandos y módulos.\n\n❓ <b>¿Cómo instalar?</b>\nPara la <b>instalación</b>, utiliza el <a href='https://xioca.ferz.live'>sitio web</a>.\n\n🌟 <b>Características:</b>\n- Control cómodo a través de comandos.\n- Soporte para modo inline.\n- Arquitectura modular para expandir funcionalidades.\n- Actualizaciones regulares y soporte.\n\n📚 <b>Documentación:</b>\nPuedes saber más sobre las funciones y la configuración en la <a href='https://github.com/shashachkaaa/Xioca'>documentación</a>.\n\n🛠 <b>Soporte:</b>\nSi tienes preguntas, contacta al <a href='https://t.me/XiocaSUPPORT'>chat de soporte</a>.",
    "inline_description": "Aprende más sobre Xioca y cómo instalarlo.",
    "inline_commands": "👇 <b>Comandos disponibles</b>\n{commands}",
    "commands_title": "Comandos disponibles",
    "inline_error": "Error",
    "installing_deps_header": "<emoji id=5884479287171485878>📦</emoji> Instalando dependencias:"
}
